
interface TradeData {
  topBuyer: string
  topFactory: string
  avgPrice: string
  totalVolume: string
  period: string
}

export const generateTradePulseReport = (data: TradeData) => {
  try {
    const reportContent = `
TRADE PULSE REPORT
Generated on: ${new Date().toLocaleDateString()}
Period: ${data.period}

=================================
KEY METRICS
=================================
Top Buyer by Volume: ${data.topBuyer}
Top Performing Factory: ${data.topFactory}
Average Price per kg: ${data.avgPrice}
Total Volume Traded: ${data.totalVolume}

=================================
MARKET INSIGHTS
=================================
• Market activity showing positive growth trend
• Premium tea grades commanding higher prices
• Consistent buyer engagement across major markets
• Factory performance varies by seasonal factors

=================================
RECOMMENDATIONS
=================================
1. Monitor seasonal price fluctuations
2. Develop stronger relationships with top buyers
3. Support high-performing factories with additional resources
4. Implement quality incentive programs

Report generated by iTea HQ Trade Pulse Analytics
    `.trim()

    const blob = new Blob([reportContent], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    
    const link = document.createElement('a')
    link.href = url
    link.download = `trade-pulse-report-${new Date().toISOString().split('T')[0]}.txt`
    link.style.display = 'none'
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    
    URL.revokeObjectURL(url)
    
    console.log('Trade Pulse report exported successfully')
    return true
  } catch (error) {
    console.error('Failed to export Trade Pulse report:', error)
    throw new Error('Export failed')
  }
}

// Enhanced admin report generator
export const generateAdminReport = () => {
  try {
    const reportContent = `
ADMIN SYSTEM REPORT
Generated on: ${new Date().toLocaleDateString()}

=================================
SYSTEM OVERVIEW
=================================
Total Users: 4
Active Users: 4
Admin Users: 1
Activity Logs: 156

=================================
USER BREAKDOWN
=================================
• Administrators: 1 user
• Approvers: 1 user  
• Initiators: 1 user
• Viewers: 1 user

=================================
SECURITY STATUS
=================================
• All users active
• No security incidents
• Regular activity monitoring enabled
• Access controls functioning properly

=================================
RECOMMENDATIONS
=================================
1. Review user permissions quarterly
2. Monitor for unusual activity patterns
3. Ensure backup procedures are current
4. Update security policies as needed

Report generated by iTea HQ Admin Center
    `.trim()

    const blob = new Blob([reportContent], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    
    const link = document.createElement('a')
    link.href = url
    link.download = `admin-report-${new Date().toISOString().split('T')[0]}.txt`
    link.style.display = 'none'
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    
    URL.revokeObjectURL(url)
    
    console.log('Admin report exported successfully')
    return true
  } catch (error) {
    console.error('Failed to export admin report:', error)
    throw new Error('Export failed')
  }
}
